[platformio]
default_envs = esp32_s3_n16r8

[env:esp32_s3_n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_port = COM24
upload_port = COM24
upload_speed = 115200
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.filesystem = spiffs
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3
  -I include
  -include optional
lib_deps =
  https://github.com/schreibfaul1/ESP32-audioI2S.git
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
